import { useMemo, useState } from 'react';
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { Activity, ArrowRight, Bell, CalendarDays, Check, ChevronRight, CircleHelp, ClipboardCheck, Clock3, HeartPulse, LayoutDashboard, LogOut, MapPin, Menu, Plus, Search, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import logo from './assets/med2sync-logo.png';
import { notifications, opportunities, roles } from './data/mockData';

const Icon = ({ children, className = '' }) => <span className={`icon ${className}`}>{children}</span>;
const Badge = ({ children, type = 'open' }) => <span className={`badge ${type}`}>{children}</span>;
const Progress = ({ value }) => <div className="progress"><span style={{ width: `${value}%` }} /></div>;

function Logo() { return <Link className="brand" to="/"><img src={logo} alt="MED2SYNC" /><span>MED2SYNC</span></Link>; }

function PublicNav() { return <header className="public-nav"><Logo /><nav><Link to="/">Home</Link><Link to="/opportunities">Opportunities</Link><a href="/#how">How it works</a><a href="/#about">About</a></nav><div className="nav-actions"><Link className="login-link" to="/login">Login</Link><Link className="button small" to="/register">Join Med2Sync <ArrowRight size={15}/></Link></div></header>; }

function Landing() { return <><PublicNav /><main>
  <section className="hero"><div className="hero-copy"><div className="eyebrow"><span /> TRUSTED HEALTHCARE COORDINATION</div><h1>Where medical<br/><em>purpose meets</em> action.</h1><p>Connect skills with opportunities. Coordinate healthcare volunteering with clarity.</p><div className="hero-buttons"><Link className="button" to="/opportunities">Explore opportunities <ArrowRight size={18}/></Link><Link className="ghost-button" to="/register">Join as a volunteer</Link></div><div className="hero-trust"><div className="avatars"><b>AP</b><b>RS</b><b>KM</b><b>+</b></div><span>Trusted by <strong>2,000+ volunteers</strong><br/>across 34 health initiatives</span></div></div>
  <div className="hero-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="pulse-core"><HeartPulse size={74}/></div><div className="float-card matching"><Sparkles size={17}/><span><small>AI-ASSISTED MATCH</small><b>92% opportunity fit</b></span></div><div className="float-card impact"><Activity size={18}/><span><small>COMMUNITY IMPACT</small><b>18,470 hours contributed</b></span></div></div></section>
  <section id="how" className="section process"><p className="kicker">A CLEARER WAY TO CONTRIBUTE</p><h2>Meaningful care, <em>better coordinated.</em></h2><p className="section-copy">MED2SYNC brings volunteers and community health programs together with transparent, skill-based coordination.</p><div className="steps">{[[Users,'Build your profile','Share your skills, preferences and availability.'],[Sparkles,'Discover your match','Explore opportunities shaped around your contribution.'],[ClipboardCheck,'Make an impact','Apply, attend and see your volunteer hours grow.']].map(([I,t,d],i)=><div className="step" key={t}><div className="number">0{i+1}</div><Icon><I size={25}/></Icon><h3>{t}</h3><p>{d}</p>{i<2&&<ChevronRight className="step-arrow"/>}</div>)}</div></section>
  <section className="feature-band"><div><p className="kicker">EXPLAINABLE, HUMAN-CENTERED</p><h2>AI-assisted matching<br/>that keeps people <em>in control.</em></h2><p>We pair your skills and availability with opportunity needs, then explain exactly why each connection may be a good fit.</p><Link className="text-link" to="/register">Explore your opportunity match <ArrowRight size={16}/></Link></div><div className="match-preview"><div className="match-head"><span>YOUR OPPORTUNITY MATCH</span><b>92<small>%</small></b></div><div className="ring"><div>92<small>%</small><span>match score</span></div></div><div className="match-row"><span>Skill alignment</span><b>95%</b><Progress value={95}/></div><div className="match-row"><span>Availability fit</span><b>85%</b><Progress value={85}/></div></div></section>
  <section className="section"><div className="section-heading"><div><p className="kicker">MAKE A DIFFERENCE</p><h2>Upcoming <em>opportunities.</em></h2></div><Link className="text-link" to="/opportunities">View all opportunities <ArrowRight size={16}/></Link></div><div className="opportunity-grid">{opportunities.map(o=><OpportunityCard key={o.id} item={o}/>)}</div></section>
  <section className="stats"><div><b>2,000<span>+</span></b><p>Active volunteers</p></div><div><b>34</b><p>Health initiatives</p></div><div><b>18.4k</b><p>Hours contributed</p></div><div><b>92<span>%</span></b><p>Volunteer satisfaction</p></div></section>
  <section id="about" className="cta"><div><p className="kicker">YOUR NEXT CONTRIBUTION STARTS HERE</p><h2>Help make care<br/><em>go further.</em></h2><p>Join a community built for thoughtful, reliable healthcare volunteering.</p></div><Link className="button light" to="/register">Join Med2Sync <ArrowRight size={18}/></Link></section>
 </main><Footer /></> }

function Footer() { return <footer><Logo/><p>Medical Volunteer Coordination Platform</p><span>© 2026 MED2SYNC. Purposefully coordinated.</span></footer> }

function OpportunityCard({ item }) { return <article className="opportunity-card"><div className="card-top"><Badge>{item.status}</Badge><span className="date"><CalendarDays size={15}/>{item.date}</span></div><h3>{item.title}</h3><p className="org">{item.organization}</p><div className="meta"><span><MapPin size={15}/>{item.location}</span><span><Users size={15}/>{item.roles} roles open</span></div><div className="tags">{item.tags.slice(0,2).map(t=><span key={t}>{t}</span>)}</div><Link to={`/opportunities/${item.id}`} className="card-link">View roles <ArrowRight size={16}/></Link></article> }

function Opportunities() { const [query,setQuery]=useState(''); const [location,setLocation]=useState('All locations'); const items=useMemo(()=>opportunities.filter(o=>(!query||o.title.toLowerCase().includes(query.toLowerCase()))&&(location==='All locations'||o.location===location)),[query,location]); return <><PublicNav/><main className="page-shell"><div className="page-intro"><p className="kicker">FIND YOUR PLACE</p><h1>Opportunities that<br/><em>move care forward.</em></h1><p>Every role supports people. Find one that suits your skills, schedule and purpose.</p></div><div className="filters"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search opportunities"/></label><select value={location} onChange={e=>setLocation(e.target.value)}><option>All locations</option><option>Bengaluru</option><option>Mysuru</option></select></div><div className="opportunity-grid listing">{items.map(o=><OpportunityCard item={o} key={o.id}/>)}</div></main><Footer/></> }

function OpportunityDetail() { const nav=useNavigate(); const o=opportunities[0]; const [applied,setApplied]=useState(false); return <><PublicNav/><main className="detail-shell"><Link className="back" to="/opportunities">← All opportunities</Link><div className="detail-head"><div><Badge>Open for volunteers</Badge><h1>{o.title}</h1><p>{o.organization}</p><div className="meta"><span><CalendarDays size={16}/>{o.date}</span><span><MapPin size={16}/>{o.location}</span></div></div><div className="detail-actions"><p>Ready to make an impact?</p><button className="button" onClick={()=>setApplied(true)}>{applied?<><Check size={18}/> Application started</>:'Apply for a role'}</button></div></div><section className="detail-content"><article><h2>About this opportunity</h2><p>{o.description} Volunteers make it possible for healthcare teams to focus on the people who need them most.</p><h2>Available volunteer roles</h2><p className="hint">You apply to a specific role, not the event directly.</p>{roles.map(r=><RoleCard key={r.id} role={r} onApply={()=>nav('/login')}/>)}</article><aside className="detail-aside"><div className="aside-card"><Sparkles size={21}/><p className="kicker">AI-ASSISTED MATCH</p><h3>See how well you fit</h3><p>Sign in to compare your profile, skills and availability with these roles.</p><Link to="/login" className="text-link">Sign in to view match <ArrowRight size={16}/></Link></div><div className="aside-card"><ShieldCheck size={21}/><h3>Good to know</h3><p>Applications are reviewed by the program administrator. You will be notified of every decision.</p></div></aside></section></main><Footer/></> }

function RoleCard({ role, onApply }) { const fill=Math.round(role.filledCount/role.capacity*100); return <div className="role-card"><div className="role-main"><h3>{role.title}</h3><p>{role.description}</p><div className="tags">{role.requiredSkills.map(s=><span key={s}>{s}</span>)}</div></div><div className="capacity"><b>{role.filledCount}<small> / {role.capacity} filled</small></b><Progress value={fill}/><button className="outline-button" onClick={onApply}>Apply <ArrowRight size={15}/></button></div></div> }

const navItems=[['Dashboard',LayoutDashboard,'/dashboard'],['Opportunities',CalendarDays,'/dashboard/opportunities'],['AI Matches',Sparkles,'/dashboard/matches'],['My Applications',ClipboardCheck,'/dashboard/applications'],['My Shifts',Clock3,'/dashboard/shifts'],['Attendance',Check,'/dashboard/attendance'],['My Profile',Users,'/dashboard/profile'],['Notifications',Bell,'/dashboard/notifications']];
function DashboardLayout({ children }) { const [open,setOpen]=useState(false); const loc=useLocation(); return <div className="dashboard"><aside className={open?'sidebar open':'sidebar'}><Logo/><div className="sidebar-label">VOLUNTEER SPACE</div>{navItems.map(([n,I,p])=><Link key={n} className={loc.pathname===p?'active':''} to={p} onClick={()=>setOpen(false)}><I size={18}/>{n}{n==='Notifications'&&<i>2</i>}</Link>)}<button className="logout"><LogOut size={18}/>Logout</button></aside><div className="dash-main"><header className="dash-top"><button className="mobile-menu" onClick={()=>setOpen(!open)}><Menu/></button><div className="crumb">Volunteer workspace <ChevronRight size={15}/> <b>{navItems.find(x=>x[2]===loc.pathname)?.[0]||'Dashboard'}</b></div><div className="top-user"><button className="bell"><Bell size={19}/><i/></button><span>AK</span><div><b>Aarav Kumar</b><small>Volunteer</small></div></div></header>{children}</div></div> }
function Stat({ label, value, icon: I, note }) { return <div className="stat-card"><Icon><I size={21}/></Icon><span>{label}</span><b>{value}</b><small>{note}</small></div> }
function DashboardHome() { return <DashboardLayout><main className="dash-content"><div className="welcome"><div><p className="kicker">FRIDAY, SEPTEMBER 26</p><h1>Good morning, Aarav <span>👋</span></h1><p>Here is how your community impact is taking shape.</p></div><Link className="button small" to="/dashboard/opportunities">Find an opportunity <ArrowRight size={16}/></Link></div><div className="stats-grid"><Stat label="Upcoming events" value="03" note="2 this month" icon={CalendarDays}/><Stat label="Pending applications" value="01" note="Awaiting review" icon={Clock3}/><Stat label="Approved applications" value="04" note="Across 3 initiatives" icon={ShieldCheck}/><Stat label="Volunteer hours" value="42.5" note="8.5 this month" icon={HeartPulse}/></div><div className="dash-grid"><section className="panel recommendations"><div className="panel-head"><div><p className="kicker">PERSONALISED FOR YOU</p><h2>AI recommended opportunities</h2></div><Link to="/dashboard/matches">See all</Link></div>{opportunities.slice(0,2).map((o,i)=><div className="recommend" key={o.id}><div className="score">{i?88:92}<small>%</small></div><div><b>{o.title}</b><p>{i?'Community Outreach':'Registration Support'} · {o.location}</p><div className="tags"><span>Skill match {i?90:95}%</span><span>Availability {i?82:85}%</span></div></div><Link to={`/opportunities/${o.id}`}><ChevronRight/></Link></div>)}</section><section className="panel next-shift"><div className="panel-head"><h2>Upcoming shift</h2><Link to="/dashboard/shifts">View all</Link></div><div className="shift-date"><b>14</b><span>OCT<br/><small>WED</small></span></div><h3>Registration Support</h3><p>Community Health Awareness Camp</p><div className="shift-info"><span><Clock3 size={15}/>09:00 AM – 01:00 PM</span><span><MapPin size={15}/>Indiranagar, Bengaluru</span></div><Badge type="approved">Confirmed</Badge></section><section className="panel activity"><div className="panel-head"><h2>Recent activity</h2><Link to="/dashboard/notifications">View all</Link></div>{notifications.map(n=><div className="activity-item" key={n.id}><Icon><Bell size={16}/></Icon><div><b>{n.title}</b><p>{n.text}</p></div><small>{n.time}</small></div>)}</section><section className="panel profile-progress"><p className="kicker">YOUR PROFILE</p><h2>Almost there</h2><div className="percent">80%</div><Progress value={80}/><p>Add your availability to improve AI recommendations.</p><Link className="text-link" to="/dashboard/profile">Complete profile <ArrowRight size={15}/></Link></section></div></main></DashboardLayout> }
function SimpleDashPage({ type }) { const data={matches:['AI opportunity matches','See transparent skill and availability scores for opportunities that fit you.'],applications:['My applications','Track the progress of every role application in one place.'],shifts:['My shifts','Your upcoming and completed volunteer commitments.'],attendance:['Attendance','Keep a clear record of your time in the community.'],profile:['My profile','Keep your skills and availability current for more relevant matches.'],notifications:['Notifications','Stay informed about every step of your volunteer journey.'],opportunities:['Explore opportunities','Find the health initiative where your contribution matters most.']}[type]; return <DashboardLayout><main className="dash-content"><div className="page-title"><p className="kicker">VOLUNTEER WORKSPACE</p><h1>{data[0]}</h1><p>{data[1]}</p></div>{type==='matches'?<MatchPanel/>:type==='opportunities'?<div className="opportunity-grid listing">{opportunities.map(o=><OpportunityCard item={o} key={o.id}/>)}</div>:<div className="empty-panel"><div><CircleHelp size={32}/></div><h2>{type==='attendance'?'No attendance records yet':'Nothing to show yet'}</h2><p>Once you start contributing, the relevant updates will appear here.</p><Link className="button small" to="/dashboard/opportunities">Explore opportunities</Link></div>}</main></DashboardLayout> }
function MatchPanel(){return <section className="match-page"><div className="match-summary"><div className="big-score">92<small>%</small></div><div><p className="kicker">TOP OPPORTUNITY</p><h2>Community Health Awareness Camp</h2><p>Registration Support · Bengaluru</p><span>Based on skills and availability in your profile.</span></div><Link className="button small" to="/opportunities/1">View role</Link></div><div className="match-breakdown"><div><span>Skill alignment</span><b>95%</b><Progress value={95}/></div><div><span>Availability fit</span><b>85%</b><Progress value={85}/></div><aside><Sparkles size={19}/><p><b>Why this match</b><br/>Your registration and communication skills closely match this role, and its weekday schedule aligns with your availability.</p></aside></div></section>}
function AdminHome(){return <DashboardLayout><main className="dash-content"><div className="welcome"><div><p className="kicker">ADMIN OVERVIEW</p><h1>Community coordination, at a glance.</h1><p>Monitor people, opportunities and the impact being made today.</p></div><Link className="button small" to="/opportunities"><Plus size={16}/>Create opportunity</Link></div><div className="stats-grid"><Stat label="Total volunteers" value="2,048" note="+18 this month" icon={Users}/><Stat label="Verified volunteers" value="1,822" note="89% verified" icon={ShieldCheck}/><Stat label="Pending applications" value="28" note="Needs review" icon={ClipboardCheck}/><Stat label="Active opportunities" value="12" note="Across 8 locations" icon={CalendarDays}/></div><div className="dash-grid"><section className="panel"><div className="panel-head"><div><p className="kicker">REQUIRES ATTENTION</p><h2>Pending applications</h2></div><Link to="/dashboard/applications">Review all</Link></div>{['Priya Sharma · Registration Support','Karan Mehta · Patient Assistance','Nisha Singh · Community Outreach'].map((x,i)=><div className="recommend" key={x}><div className="score">0{i+1}</div><div><b>{x}</b><p>Community Health Awareness Camp · Submitted today</p></div><button className="outline-button" style={{width:'auto'}}>Review</button></div>)}</section><section className="panel profile-progress"><p className="kicker">AI-ASSISTED MATCHING</p><h2>Strong coverage</h2><div className="percent">86%</div><Progress value={86}/><p>Open roles have at least one highly compatible volunteer.</p><Link className="text-link" to="/dashboard/matches">Review matches <ArrowRight size={15}/></Link></section><section className="panel activity"><div className="panel-head"><h2>Recent volunteers</h2><Link to="/dashboard/profile">View directory</Link></div>{['Devika Nair','Rahul Joshi','Maya Iyer'].map((x,i)=><div className="activity-item" key={x}><Icon><Users size={16}/></Icon><div><b>{x}</b><p>Profile {i===1?'pending verification':'verified'} · Bengaluru</p></div><small>{i+1}h ago</small></div>)}</section><section className="panel next-shift"><div className="panel-head"><h2>Quick actions</h2></div><Link className="card-link" to="/opportunities">Create an opportunity <ArrowRight size={15}/></Link><Link className="card-link" to="/dashboard/applications">Review applications <ArrowRight size={15}/></Link><Link className="card-link" to="/dashboard/matches">Find volunteer matches <ArrowRight size={15}/></Link></section></div></main></DashboardLayout>}
function Auth({ registerMode=false }) { const nav=useNavigate(); const [email,setEmail]=useState(registerMode?'':'volunteer@medvol.com'); const [password,setPassword]=useState(registerMode?'':'Volunteer@123'); const submit=e=>{e.preventDefault(); nav(email.startsWith('admin@')?'/admin/dashboard':'/dashboard')}; return <main className="auth"><Link className="auth-logo" to="/"><img src={logo} alt="MED2SYNC"/><span>MED2SYNC</span></Link><section className="auth-card"><p className="kicker">{registerMode?'START YOUR JOURNEY':'WELCOME BACK'}</p><h1>{registerMode?'Join MED2SYNC':'Sign in to MED2SYNC'}</h1><p>{registerMode?'Create your volunteer profile and find your place in healthcare impact.':'Use your account to continue to your volunteer workspace.'}</p><form onSubmit={submit}>{registerMode&&<label>Full name<input required placeholder="Your full name"/></label>}<label>Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label><button className="button full">{registerMode?'Create volunteer account':'Sign in'} <ArrowRight size={17}/></button></form><p className="auth-foot">{registerMode?'Already have an account?':'New to MED2SYNC?'} <Link to={registerMode?'/login':'/register'}>{registerMode?'Sign in':'Join now'}</Link></p></section><p className="auth-bottom">© 2026 MED2SYNC · Coordinating care with clarity</p></main> }
function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/opportunities" element={<Opportunities/>}/><Route path="/opportunities/:id" element={<OpportunityDetail/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth registerMode/>}/><Route path="/dashboard" element={<DashboardHome/>}/><Route path="/admin/dashboard" element={<AdminHome/>}/>{['matches','applications','shifts','attendance','profile','notifications','opportunities'].map(p=><Route key={p} path={`/dashboard/${p}`} element={<SimpleDashPage type={p}/>}/>) }<Route path="*" element={<Navigate to="/"/>}/></Routes>}
export default App;
